openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:9090
    description: Generated server url
paths:
  /api/wallet:
    get:
      tags:
        - wallet-controller
      operationId: getAllWallets
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WalletDTO'
    post:
      tags:
        - wallet-controller
      operationId: createWallet
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWalletDTO'
        required: true
      responses:
        "500":
          description: Internal Server Error
          content:
            '*/*':
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WalletDTO'

components:
  schemas:
    CreateWalletDTO:
      required:
        - name
      type: object
      properties:
        name:
          maxLength: 20
          minLength: 0
          pattern: "[a-z A-Z]+"
          type: string
    WalletDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        creationDate:
          type: string
          format: date-time
